/* Shared TDG Route data, printing and account-scoped storage. */
(()=>{'use strict';
const text=v=>v==null?'':String(v).trim();
const first=(...values)=>values.find(v=>text(v)!=='')??'';
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
async function paged(query){const rows=[];let offset=0;query=query.order('id',{ascending:true});for(;;){const r=await query.range(offset,offset+499);if(r.error)return {data:null,error:r.error};if(!Array.isArray(r.data))return {data:null,error:new Error('Invalid database response')};if(!r.data.length)return {data:rows,error:null};rows.push(...r.data);offset+=r.data.length;}}
function resolveShift(records=[],dailyLog,shift){const form=dailyLog?.payload?.form||{},saved=dailyLog?.payload?.shift||{};const startKm=first(form.startKm,shift?.start_km,...records.map(r=>first(r.start_km,r.raw?.startKm)));const endKm=first(form.endKm,...[...records].reverse().map(r=>first(r.end_km,r.raw?.endKm)));return {startKm,endKm,totalKm:text(startKm)!==''&&text(endKm)!==''?Number(endKm)-Number(startKm):'',shiftStart:first(shift?.check_in_time,form.shiftTimeStart,form.shiftStart,saved.start,...records.map(r=>first(r.shift_start,r.shiftStart,r.raw?.shiftStart,r.raw?.shiftTimeStart))),shiftFinish:first(shift?.check_out_time,form.shiftTimeFinish,form.shiftFinish,saved.finish,...[...records].reverse().map(r=>first(r.shift_finish,r.shiftFinish,r.raw?.shiftFinish,r.raw?.shiftTimeFinish)))};}
async function loadShiftContext(sb,ownerId,date,vehicleNo){if(!ownerId||!date)throw new Error('Daily Log identity missing');const [logs,shifts]=await Promise.all([paged(sb.from('tdg_daily_logs').select('*').eq('owner_id',ownerId).eq('log_date',date).order('created_at',{ascending:true})),sb.from('tdg_shift_sessions').select('*').eq('owner_id',ownerId).eq('work_date',date).eq('vehicle_no',vehicleNo).maybeSingle()]);if(logs.error||shifts.error)throw logs.error||shifts.error;return {dailyLog:logs.data.filter(r=>text(r.vehicle_no||r.payload?.vehicleNo||r.payload?.form?.vehicleNo)===text(vehicleNo)).at(-1)||null,shift:shifts.data};}
let owner=null;const scoped=native=>({getItem(k){return owner?native.getItem(`tdg:user:${owner}:${k}`):null;},setItem(k,v){if(!owner)throw new Error('Validated login required');native.setItem(`tdg:user:${owner}:${k}`,v);},removeItem(k){if(owner)native.removeItem(`tdg:user:${owner}:${k}`);},clear(){if(!owner)return;const p=`tdg:user:${owner}:`;for(let i=native.length-1;i>=0;i--){const k=native.key(i);if(k?.startsWith(p))native.removeItem(k);}}});
window.TDG_STORAGE=scoped(window.localStorage);window.TDG_SESSION_STORAGE=scoped(window.sessionStorage);const bindUser=id=>{owner=id||null;};
async function openingBalance(sb,ownerId,date,vehicleNo,currentRecords=[]){const volume=window.TDG_VOLUME;if(!volume)throw new Error('Missing volume rules');const reset=volume.isResetVehicle(vehicleNo)&&date>=volume.RESET_DATE;let q=sb.from('tdg_records').select('*').eq('owner_id',ownerId).eq('vehicle_no',vehicleNo).lt('work_date',date).order('work_date',{ascending:true}).order('completed_at',{ascending:true});if(reset)q=q.gte('work_date',volume.RESET_DATE);const r=await paged(q);if(r.error)throw r.error;const base=reset?0:volume.getTdgStartKg(r.data[0]||currentRecords[0]);if(base==null)throw new Error('No verified opening balance');return r.data.reduce((n,row)=>n+volume.getReloadAmountKg(row)-(volume.getAdjustmentAmountLbs(row)+(Number(row.delivered_volume)||0))*0.45359237,base);}
window.TDG_CORE={text,first,escapeHtml,localDate,paged,resolveShift,loadShiftContext,bindUser,openingBalance};
})();
