import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.111.0';
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json','Cache-Control':'no-store'};
export const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers});
export const clean=v=>String(v??'').trim();
export function clients(){const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),anon=Deno.env.get('SUPABASE_ANON_KEY');if(!url||!key||!anon)throw new Error('Server configuration missing');const options={auth:{persistSession:false,autoRefreshToken:false}};return {admin:createClient(url,key,options),user:createClient(url,anon,options)};}
export async function identity(req,adminOnly=true){const {admin,user}=clients(),token=(req.headers.get('Authorization')||'').match(/^Bearer (.+)$/i)?.[1];if(!token)throw new Error('Unauthorized');const u=await user.auth.getUser(token);if(u.error||!u.data.user)throw new Error('Unauthorized');const p=await admin.from('tdg_profiles').select('*').eq('id',u.data.user.id).single();if(p.error||!p.data?.is_active||(adminOnly&&(p.data.role!=='admin'||p.data.must_change_password)))throw new Error('Access denied');return {admin,user,caller:u.data.user,profile:p.data};}
export function serve(handler){Deno.serve(async req=>{if(req.method==='OPTIONS')return json({ok:true});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{return await handler(req);}catch(error){const message=error instanceof Error?error.message:'Request failed';return json({error:message},message==='Unauthorized'?401:message==='Access denied'?403:400);}});}
export function password(value){const p=String(value??'');if(p.length<12||p.length>128)throw new Error('Password requires 12–128 characters');return p;}
export function validProfile(body,old={}){if([body.isActive,body.is_active,body.mustChangePassword].some(v=>v!==undefined&&typeof v!=='boolean'))throw new Error('Invalid boolean field');const driver=clean(body.driverNumber??old.driver_number).toLowerCase(),name=clean(body.displayName??old.display_name),role=clean(body.role??old.role??'driver'),email=clean(body.email??old.email).toLowerCase(),vehicle=clean(body.vehicleNo??old.vehicle_no),phone=clean(body.phone??old.phone);if(!/^[a-z0-9._-]{2,32}$/.test(driver)||!name||name.length>60||!['admin','driver','viewer'].includes(role)||!/^\S+@\S+\.\S+$/.test(email)||email.length>120||vehicle.length>40||phone.length>40)throw new Error('Invalid profile fields');return {username:driver,driver_number:driver,display_name:name,role,email,vehicle_no:vehicle,phone,is_active:body.isActive??body.is_active??old.is_active??true,must_change_password:old.must_change_password||Boolean(body.mustChangePassword)};}
export async function withAccountOperation(admin,targetId,work){const args={target_id:targetId,operation_token:crypto.randomUUID()},acquired=await admin.rpc('tdg_acquire_account_operation',args);if(acquired.error)throw new Error('Could not reserve account operation');if(!acquired.data)throw new Error('Another account operation is in progress. Retry after it completes.');try{return await work();}finally{const r=await admin.rpc('tdg_release_account_operation',args);if(r.error||!r.data)throw new Error('Account operation ended, but release was not confirmed. Refresh and ask an administrator to inspect the reservation.');}}
