const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'..');
function storage(){const m=new Map;return {get length(){return m.size},key:i=>[...m.keys()][i],getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
const els={},el=id=>els[id]||={value:'',textContent:'',style:{},dataset:{},classList:{add(){},remove(){},contains(){return true}},focus(){},addEventListener(){}};
const c={console:{log(){},warn(){},error(){}},document:{addEventListener(){},getElementById:el},localStorage:storage(),sessionStorage:storage(),Date,Math,JSON,Number,Map,Set,crypto:require('crypto').webcrypto,alert(){},confirm:()=>true,setTimeout(){},clearTimeout(){},navigator:{},location:{},addEventListener(){}};c.window=c;c.TDG_AUTH={getSession:()=>({userId:'u',role:'driver',driverNumber:'d',displayName:'D'})};vm.createContext(c);
for(const f of ['tdg_core.js','tdg_volume.js','app_supabase.js'])vm.runInContext(fs.readFileSync(root+'/js/'+f,'utf8'),c);c.TDG_CORE.bindUser('u');const run=s=>vm.runInContext(s,c);let n=0;async function test(name,fn){await fn();console.log('PASS '+name);n++;}
(async()=>{
await test('browser scripts parse',()=>{for(const f of fs.readdirSync(root,{recursive:true})){if(f.startsWith('supabase/')||! /\.(js|html)$/.test(f))continue;const s=fs.readFileSync(root+'/'+f,'utf8');for(const t of f.endsWith('.js')?[s]:[...s.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>!m[1].includes('src=')).map(m=>m[2]))new vm.Script(t,{filename:f});}});
await test('off-duty shift table overrides empty records',()=>assert.equal(c.TDG_CORE.resolveShift([{shift_finish:''}],null,{check_out_time:'17:25'}).shiftFinish,'17:25'));
await test('off-duty final form fallback',()=>assert.equal(c.TDG_CORE.resolveShift([{shift_finish:''}],{payload:{form:{shiftTimeFinish:'16:10'}}}).shiftFinish,'16:10'));
await test('off-duty payload.shift fallback',()=>assert.equal(c.TDG_CORE.resolveShift([],{payload:{shift:{finish:'18:30'}}}).shiftFinish,'18:30'));
await test('off-duty raw nonempty fallback',()=>assert.equal(c.TDG_CORE.resolveShift([{shift_finish:'',raw:{shiftTimeFinish:'15:00'}}]).shiftFinish,'15:00'));
await test('zero odometer preserved',()=>assert.equal(c.TDG_CORE.resolveShift([],{payload:{form:{startKm:0,endKm:25}}}).totalKm,25));
await test('account cache isolation',()=>{c.TDG_STORAGE.setItem('x','alice');c.TDG_CORE.bindUser('b');assert.equal(c.TDG_STORAGE.getItem('x'),null);c.TDG_CORE.bindUser('u');assert.equal(c.TDG_STORAGE.getItem('x'),'alice')});
await test('HTML escaping',()=>assert.equal(c.TDG_CORE.escapeHtml('<img onerror="x">&'),'&lt;img onerror=&quot;x&quot;&gt;&amp;'));
await test('pagination handles 1073 rows with 127 server cap',async()=>{const rows=Array.from({length:1073},(_,id)=>({id}));const q={order(){return this},range(a,b){return Promise.resolve({data:rows.slice(a,Math.min(a+127,b+1))})}};assert.equal((await c.TDG_CORE.paged(q)).data.length,1073)});
await test('pagination errors do not return partial success',async()=>{let i=0;const q={order(){return this},range(){return Promise.resolve(++i===1?{data:[{}]}:{error:new Error('offline')})}};assert.equal((await c.TDG_CORE.paged(q)).data,null)});
const admin=fs.readFileSync(root+'/js/admin.js','utf8');run(admin.slice(admin.indexOf('  function parseCsv('),admin.indexOf('  const Api =')));
await test('CSV quoted commas and newlines',()=>{const r=run(`parseCsv('id,name,address\\n001,"Acme, Inc","A\\nB"')`);assert.equal(r[0].name,'Acme, Inc');assert.equal(r[0].address,'A\nB')});
await test('invalid CSV rejected',()=>{assert.throws(()=>run(`parseCsv('a,b\\n"bad,b')`));assert.throws(()=>run(`parseCsv('a,b\\n1,2,3')`))});
await test('DST and backwards calendar weeks',()=>{process.env.TZ='America/Winnipeg';assert.equal(run('computeWeekCycleFromAnchor({cycle:1,weekStart:new Date(2026,2,2)},new Date(2026,2,9))'),2);assert.equal(run('computeWeekCycleFromAnchor({cycle:1,weekStart:new Date(2026,2,9)},new Date(2026,2,2))'),8)});
await test('reverse odometer blocks off-duty',()=>{el('startKm').value='100';el('endKm').value='90';run(`shiftFinish='16:00'`);assert.equal(run('validateOffDutyRequiredFields().ok'),false)});
await test('exact kg balance retained',()=>assert.equal(run('computeRemainingTDG(100,[{deliveredVolume:1}]).remainingExactKg'),99.54640763));
let inserts=0,lost=true,rows=new Map;c.supabaseClient={auth:{getUser:async()=>({data:{user:{id:'u'}}})},from(){let row=null,filters=[];const q={insert(r){row=r;return q},select(){return q},eq(k,v){filters.push([k,v]);return q},single(){return q},maybeSingle(){return q},then(resolve,reject){let r;if(row){inserts++;if(rows.has(row.client_record_id))r={error:{code:'23505'}};else{rows.set(row.client_record_id,{...row,id:'remote1'});if(lost){lost=false;return Promise.reject(new Error('Lost response')).then(resolve,reject)}r={data:rows.get(row.client_record_id)}}}else r={data:[...rows.values()].find(x=>filters.every(([k,v])=>x[k]===v))};return Promise.resolve(r).then(resolve,reject)}};return q}};
const record={date:'2026-09-08',vehicleNo:'82303',accountNumber:'001',arrivalTime:'10:00',deliveredVolume:10,notes:'test'};
await test('lost response retains durable outbox',async()=>{await assert.rejects(()=>c.syncRecordToSupabase(record));assert.equal(c.readOutbox().length,1);assert.equal(rows.size,1)});
await test('retry neither duplicates nor overwrites',async()=>{await c.syncRecordToSupabase({...record});assert.equal(rows.size,1);assert.equal(c.readOutbox().length,0)});
await test('remote edit cannot be overwritten by old upload',async()=>{rows.get(record.clientRecordId).delivered_volume=99;await assert.rejects(()=>c.syncRecordToSupabase({...record}));assert.equal(rows.get(record.clientRecordId).delivered_volume,99);c.writeOutbox([])});
await test('negative delivery cannot upload',async()=>await assert.rejects(()=>c.syncRecordToSupabase({...record,clientRecordId:'negative',deliveredVolume:-1})));
await test('quota failure prevents network write',async()=>{const before=inserts,save=c.TDG_STORAGE.setItem;c.TDG_STORAGE.setItem=()=>{throw new Error('Quota')};await assert.rejects(()=>c.syncRecordToSupabase({...record,clientRecordId:'quota',accountNumber:'002'}));assert.equal(inserts,before);c.TDG_STORAGE.setItem=save});
await test('failed sync prevents off-duty completion',async()=>{run(`setRecords([{clientRecordId:'r',synced:false}]);syncRecordToSupabase=async()=>{throw new Error('offline')}`);await assert.rejects(()=>run('syncAllLocalRecordsToSupabase()'));assert.equal(run('getRecords()[0].synced'),false)});
console.log(`${n} core/queue scenarios passed`);
})().catch(e=>{console.error(e);process.exitCode=1});
